"""The recipe is asserted, not only described. R229 §0(b).

WHY A DIGEST NEEDS A TEST AND NOT JUST A DOCSTRING. `15dc83c78950d42b…` was this
project's portability evidence for roughly fifteen rounds and cannot be
regenerated by anyone: sixteen plausible conventions over the five stored output
bodies, and none of them produces it. The bodies agree with each other, so the
finding it supported stands; the recipe that turned them into that number is
gone. A prose description of a recipe decays the same way -- the file that
described it is the file that would have to be maintained.

So each clause of the recipe is a test here, and each fails loudly if the
convention drifts. What is protected is not the VALUE -- that legitimately moves
when the tool's output changes -- but the RULE by which a value is produced, which
is what makes any two values comparable.

AND THE INPUTS ARE IN THE REPOSITORY. The retired measurement read its frames
from a session scratch directory, so nobody but its author could have reproduced
it even holding the recipe. `tests/phase1/portability_data/` fixes that: two CSVs
and the pipeline, carried in verbatim rather than rewritten, so this digest stays
continuous with the bodies the original runs produced.
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
for p in (str(ROOT), str(ROOT / "src"), str(ROOT / "tools")):
    if p not in sys.path:
        sys.path.insert(0, p)

import portability_digest as pdg                                  # noqa: E402

DATA = ROOT / "tests" / "phase1" / "portability_data"


def test_the_inputs_are_in_the_REPOSITORY_not_in_a_scratch_directory():
    """The defect that made the old number unreproducible by anyone else."""
    for name in ("stations.csv", "scans.csv", "pipeline.py"):
        p = DATA / name
        assert p.is_file(), (
            "%s is missing, so this digest can only be produced by whoever has "
            "the file. That is what made the retired one unreproducible." % name)
    assert "def build" in (DATA / "pipeline.py").read_text(encoding="utf-8")


def test_the_recipe_is_LF_one_trailing_LF_utf8_sha256():
    """Each clause, checked against a known body rather than described."""
    body = ["b", "a", "c"]
    expected = hashlib.sha256(b"b\na\nc\n").hexdigest()
    assert pdg.digest(body) == expected, (
        "the join, the trailing separator, the encoding or the algorithm has "
        "changed, so this digest is no longer comparable with any earlier one")

    # and each wrong convention is genuinely different, so the test has teeth
    for wrong in (b"b\na\nc", b"b\r\na\r\nc\r\n", b"bac", b"b\na\nc\n\n"):
        assert hashlib.sha256(wrong).hexdigest() != expected


def test_the_digest_does_NOT_depend_on_the_banner():
    """The banner is the variable; the body is the measurement. A digest that
    moved with the interpreter version would report every environment as
    different and could never be portability evidence."""
    body = pdg.canonical_body()
    assert pdg.digest(body) == pdg.digest(list(body))
    env = pdg.environment()
    assert any("python" in e for e in env), env
    for line in body:
        assert not line.startswith("# "), (
            "a banner line reached the hashed body: %r" % line)


def test_every_collection_in_the_body_is_SORTED():
    """Nothing may depend on dict or set iteration order, or the digest differs
    between runs of the same code and stops meaning anything."""
    body = pdg.canonical_body()
    i = body.index("--- findings, canonical order ---")
    j = body.index("--- notes, canonical order ---")
    findings, notes = body[i + 1:j], body[j + 1:]
    assert findings == sorted(findings), "findings are not sorted"
    assert notes == sorted(notes), "notes are not sorted"
    for prefix in ("FEATURES     ", "BASE_COLUMNS "):
        line = [b for b in body if b.startswith(prefix)][0]
        items = line[len(prefix):].split(",")
        assert items == sorted(items), "%s is not sorted: %r" % (prefix, items)


def test_the_body_is_STABLE_across_two_calls_in_one_process():
    """The cheapest possible check that the run is deterministic at all. It
    would have caught a seed that was not fixed."""
    assert pdg.digest(pdg.canonical_body()) == pdg.digest(pdg.canonical_body())


def test_the_module_states_what_the_digest_is_NOT_evidence_for():
    """A digest is the most authoritative-looking unframed figure there is, and
    the retired one survived fifteen quotations partly on that. The bound
    travels with the instrument."""
    doc = pdg.__doc__ or ""
    assert "NOT evidence" in doc
    for bound in ("fixture", "second machine"):
        assert bound in doc, "the stated bound omits %r" % bound
