"""The portability digest, and the recipe that produces it. R229 §0.

    py -3.12 tools/portability_digest.py
    <corner-venv>\\Scripts\\python.exe tools/portability_digest.py

WHY THIS FILE EXISTS. The digest quoted as this project's portability evidence
for roughly fifteen rounds -- `15dc83c78950d42b…` -- **cannot be regenerated by
anyone, including its author**. The five stored output bodies from the original
runs hash identically to one another under every convention tried (sixteen of
them: LF and CRLF joins, with and without a trailing separator, banner included
and excluded, raw bytes, stripped bytes, and from the `VERDICT` offset), and none
of those hashes begins `15dc83c7`. The artifacts agree with each other and with
the finding they supported; what was lost is the recipe that turned them into the
published number.

**A bare hash is the most authoritative-looking unframed figure there is**, which
is why that one survived fifteen quotations unchallenged. So this file does two
things a scratch script did not: it prints the digest, and it prints the recipe
next to it, from the code that computed it.

THE RECIPE, and it is asserted by a test rather than described here only:

  * WHAT IS HASHED  the canonical body below -- every line this file prints
                    between the BODY markers, and nothing else. The version
                    banner is EXCLUDED, because the banner is the variable and
                    the body is the measurement.
  * ORDERING        every collection is sorted before rendering: features, notes,
                    per-combination pairs, base columns, and the findings, each
                    rendered as `feature|cohort|detector|promotion|strategies`
                    with its strategies sorted. Nothing depends on dict or set
                    iteration order.
  * LINE ENDINGS    lines joined with a single "\\n". Never the platform's.
  * TRAILING        exactly one "\\n" after the last body line.
  * ENCODING        UTF-8, no BOM.
  * ALGORITHM       sha256, lowercase hex, printed in full.

WHAT THE DIGEST IS EVIDENCE FOR. That the probe's answer does not depend on its
environment: the same source, imported from `src`, run over the same inputs, with
only the interpreter and the dependency set varying. It is NOT evidence about the
fixture path, about a second machine, or about any environment not listed in the
run that produced it.
"""
from __future__ import annotations

import hashlib
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
DATA = REPO / "tests" / "phase1" / "portability_data"

for _p in (str(REPO), str(REPO / "src")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

BODY_BEGIN = "--- BODY BEGIN ---"
BODY_END = "--- BODY END ---"


def build(frames):
    """The pipeline under test -- `tests/phase1/portability_data/pipeline.py`.

    CARRIED IN VERBATIM RATHER THAN REWRITTEN, so this digest is continuous with
    the bodies the original runs produced. A better-written pipeline here would
    measure a different thing and quietly break comparability with the five
    stored outputs, which is the only tie left to the retired number.

    The inputs are committed beside it. The old measurement read them from a
    session scratch directory, which is why nobody but its author could ever have
    reproduced it even with the recipe in hand.
    """
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "_portability_pipeline", DATA / "pipeline.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.build(frames)


def canonical_body() -> list[str]:
    """The lines that are hashed. Every collection sorted before rendering."""
    import pandas as pd

    from leakaudit.availability import AvailabilityModel, run_probe_a
    from leakaudit.availability_trace import traces_for
    from leakaudit.findings import AuditResult

    raw = {"stations": pd.read_csv(DATA / "stations.csv"),
           "scans": pd.read_csv(DATA / "scans.csv")}
    model = AvailabilityModel(aggregate_frames={"scans": "scanned_at"},
                              decision_column="timestamp")
    res = run_probe_a(raw, build, model, side="user",
                      cohort_stride=97, max_cohorts=400, seed=20260828)
    out = AuditResult(traces_for(res, [c.second for c in res.cohorts],
                                 case_id="user"), source=res)

    lines = [
        "VERDICT      %s" % out.outcome,
        "COHORTS      %d" % len(out.cohorts_probed),
        "FINDINGS     %d" % len(out.findings),
        "FEATURES     %s" % ",".join(sorted({f.feature for f in out.findings})),
        "PER_COMB     %s" % ";".join("%s=%s" % kv for kv in
                                     sorted(out.per_combination.items())),
        "BASE_COLUMNS %s" % ",".join(sorted(res.base_columns)),
        "--- findings, canonical order ---",
    ]
    lines += sorted(
        "%s|%s|%s|%s|%s" % (f.feature, f.affected_output_cohort, f.detector,
                            f.promotion_status, ",".join(sorted(f.strategies)))
        for f in out.findings)
    lines.append("--- notes, canonical order ---")
    lines += sorted(out.notes)
    return lines


def digest(lines: list[str]) -> str:
    """THE RECIPE, IN CODE. "\\n" joins, one trailing "\\n", UTF-8, sha256."""
    return hashlib.sha256(("\n".join(lines) + "\n").encode("utf-8")).hexdigest()


def environment() -> list[str]:
    import numpy
    import pandas
    import pyarrow
    return ["python  %s" % sys.version.split()[0],
            "numpy   %s" % numpy.__version__,
            "pandas  %s" % pandas.__version__,
            "pyarrow %s" % pyarrow.__version__,
            "exe     %s" % sys.executable]


def main() -> int:                                           # pragma: no cover
    for line in environment():
        print("# %s" % line)
    print("#")
    body = canonical_body()
    print(BODY_BEGIN)
    for line in body:
        print(line)
    print(BODY_END)
    print()
    print("RECIPE   sha256 over the %d body lines above, joined with a single"
          % len(body))
    print("         LF, one trailing LF, encoded UTF-8. Banner excluded.")
    print("DIGEST   %s" % digest(body))
    return 0


if __name__ == "__main__":                                   # pragma: no cover
    raise SystemExit(main())
